spring:
  application:
    name : finalwork

  datasource:
    url: jdbc:mysql://localhost:3306/bms?useSSL=false&serverTimezone=Asia/Shanghai  #
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      client: jedis  # ???????????? spring.redis.client-type?
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}  # ???????????
      database: 0
      timeout: 10000ms  # ????
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms  # -1 ??????
  mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
