server:
  port: 31777

# API 端点
api:
  endpoint:
    url: http://localhost:31777/api/warning/calculate

  # 批量处理配置
batch:
  size: 500
timeout:
  seconds: 5


spring:
  application:
    name : finalwork
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      client: jedis
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000ms
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  rabbitmq:
    queue: car-signal-queue
    host: localhost
    port: 5672
    username: guest
    password: guest

  task:
    scheduling:
      pool:
        size: 5
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: my_battery_signal_producer_group
#  consumer:
#    group: my_battery_signal_consumer_group
#    thread-count: 10
#  topic:
#    battery-signal: battery_signal_topic
