spring:
  application:
    name : finalwork

  datasource:
    url: jdbc:mysql://localhost:3306/bms?useSSL=false&serverTimezone=Asia/Shanghai  #
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      client: jedis
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms  # ????
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000ms  # -1 ??????
  mybatis:
    configuration:
      map-underscore-to-camel-case: true


  task:
    scheduling:
      pool:
        size: 5
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:

rocketmq:
  name-server: localhost:9876
  producer:
    group: my_battery_signal_producer_group
  consumer:
    group: my_battery_signal_consumer_group
warn:
  rocketmq:
    topic: battery_signal_topic
